"""Added relationships and validations

Revision ID: 75d43fd077b4
Revises: 4d67f778461c
Create Date: 2025-06-06 12:45:17.558892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d43fd077b4'
down_revision = '4d67f778461c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
